name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace --all-targets
    - name: Build
      run: cargo clippy --workspace --all-targets
    - name: Load vcan kernel module
      run: |
        ls -R /lib/modules/6.5.0-1025-azure
        sudo modprobe vcan
    - name: Run tests
      run: cargo test --workspace --all-targets
