name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --workspace --all-targets
    - name: Clippy
      run: cargo clippy --workspace --all-targets
    - name: Tests
      run: cargo test --workspace --all-targets
